version: '3.8'
networks:
  appnet:
volumes:
  node_modules:
services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_VERSION=${NODE_IMAGE_VERSION}
    ports:
      - '3000:3000'
    volumes:
      - type: bind
        source: ./
        target: /home/node/app
      - type: volume
        source: node_modules
        target: /home/node/app/node_modules
    depends_on:
      - db
    networks:
      - appnet
    environment:
      MONGO_CONNECTION_STRING: mongodb://database:27017
    env_file:
      - .env
  db:
    image: mongo:${MONGO_IMAGE_VERSION}
    networks:
      appnet:
        aliases:
          - database
