version: '3.8'

networks:
  appnet:

volumes:
  node_modules:
  database:

services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_VERSION=${NODE_IMAGE_VERSION}
    command: npm run containerized
    networks:
      - appnet
    ports:
      - 3000:3000
    volumes:
      - type: bind
        source: ./
        target: /home/app
      - type: volume
        source: node_modules
        target: /home/app/node_modules
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:${POSTGRES_IMAGE_VERSION}
    networks:
      appnet:
        aliases:
          - database
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - type: volume
        source: database
        target: /var/lib/postgresql/data
    ports:
      - 5432:5432
